### ISSUE TITLE
Maybe join effort with phone_numbers_parser

### ISSUE THREAD

**Issue by cedvdb** [superakabo/dlibphonenumber#3]
You may want to be a maintainer for  https://pub.dev/packages/phone_numbers_parser ?

Imo it would be better to join force than to duplicate efforts over there and here. The above library is older and is not a one to one port though

**Comment by superakabo** [comment]
Hi @cedvdb, the two packages do the same thing but they are actually quite different under the hood.
[phone_numbers_parser](https://pub.dev/packages/phone_numbers_parser) relies on platform channels. It uses [libphonenumber](https://github.com/google/libphonenumber) for android and [PhoneNumberKit](https://github.com/marmelroy/PhoneNumberKit) for iOS. Mine is better because it is a pure dart implementation and does not depend on any 3rd party library. Hope this helps.

**Comment by cedvdb** [comment]
No it's not phone_number_parser is pure dart. I'm the author of the package.

**Comment by superakabo** [comment]
OK that's cool.

**Comment by cedvdb** [comment]
If you are interested in becoming a maintainer now or in the future just let me know. No need to duplicate efforts. 😊
